### ISSUE TITLE
Remember me button 

### ISSUE THREAD

**Issue by D00ktora** [luchob/softuni-sep-2023#11]
Лъчо , понеже няма вариант а отворен въпрос. Затова в графа какво искаме да видим питам. Понеже вчера трябваше да си прибера детето и не догледах лекцията. Та за това как се сетива този бутон запомни ме, при спфтуни например за да е сигурно и да не изтича информация? 
може ли да го видим в следващата лекция?

**Comment by luchob** [comment]
Здравей!

Не, не може да го видим в следващата лекция :D Причината е, че както и това, така и самия ни логин в момента са неправилно реализирани в спринг контекст. Би трябвало да се реализират с помощта на спринг секюрити, напр. -> https://docs.spring.io/spring-security/reference/servlet/authentication/rememberme.html

Оставям въпроса отворен за следващата част, където е и спринг секюрити.

Поздрави,
Л.

**Comment by luchob** [comment]
Демонстрирано :-)
