### ISSUE TITLE
Проблем с качването на проект от IntelliJ в Github

### ISSUE THREAD

**Issue by emil2romanov** [luchob/softuni-sep-2023#12]
*Връзка към проекта:*

https://github.com/emil2romanov/Mobilele2023

*Кратко описание:*

Възможно най-накратко опишете:

1.Когато качвам проекта искам да се качи, както се качва при теб. Искам да се качи като папка 'mobilele', вътре в нея да са класовете, пекиджите и другите файлове. Идеята ми беше това репозитори да е за курса, и да се качват отделните проекти по лекции като папки.
![Screenshot (80)](https://github.com/luchob/softuni-sep-2023/assets/118777918/ee08d728-d933-43eb-91e5-8162f4112ab6)
![Screenshot (81)](https://github.com/luchob/softuni-sep-2023/assets/118777918/bd7e74d0-690f-4a5d-bac4-30f580596288)

2. Но се качва всичко накуп без да са в папката 'mobilele' и затова оставих репозиторито само за проекта 'mobilele'
3. Опитах различни начини да commit-на и push-на, но не успях да го променя това.

*Стъпки за репродуциране:*

Опишете възможно най-лесните стъпки, с помощта на които може да се репродуцира проблемът.

**Comment by luchob** [comment]
Здравей, Емо!

Според мен този лейаут е идеален -> https://github.com/emil2romanov/Mobilele2023

Казвам го, защото:

1. Може лесно да го свалям ако има проблем, без да ми се налага да свалям какво ли не още.
2. Бих искал да ви покажа някои благини - например някой github action за билд и тест на проектчето, както и основна работа с dependabot. Това са тулчета, с които ще надникнете поне малко в CI/CD света и лейаута е много подходящ за тяхната употреба.


Ако все пак държиш да е подобен лейаута на моя, с отделни папки, най-лесното е:

1. Направи си рипозитори.
2. Вътре направи 1 папка за мобилеле + 2-3-4 папки за други неща.
3. Комитвай в тези 2-3-4 папки с каквото е удобно (конзола,  някякъв редактор, IntelliJ и т.н.). Можеш да комитваш от руут папката на репозиторито, което си чекаутнал локално.
4. Отваряй репото на мобилеле с IntelliJ директно, не от руут папката в репозиторито а по-скоро от папката с мобилеле.

Това няма да е особено удобно, т.к. ще виждаш и комити от другите папки.

Препоръчвам ти да си държиш мобилелето в отделно репо на този етап, но решението е твое.

Поздрави,
Л.

П.П. Наскоро колежката Фо говори за гит в един talk в java user групата на БГ. Вероятно може да го намериш за полезено: 

https://www.youtube.com/watch?v=s2buYWqx4Bw

**Comment by emil2romanov** [comment]
Благодаря за подробния отговор. Ще изгледам клипа със сигурност. 

Имам един проект, който правя със Spring и Angular. Въпросът го зададох включително и за там, защото искам да го разделя на две папки - "backend" и "frontend". В момента там ми качен само бекенда -> https://github.com/emil2romanov/ECommerceProject
Но тъй като се качи така бекенда (като при мобилелето), фронтенда не го качих ... какъв вариант имам сега да ги разделя на две папки ...  или какво решение предлагаш ти. 

Mobilele проекта ще го оставя така както е в момента. 
Поздрави

**Comment by luchob** [comment]
Здравей!

Ние също имаме такива приложения и обикновено ги държим всяко в отделно репозитори. Поне за нас работи добре. Разликата е, че понякога имаме повече от 1 бекенд за 1 фронтенд :-) 

В твоя случай може да се спреш на някой от вариантите, например:

Вариант 1 (според мен е по-удачен):

1. Направи нови репозиторита за бекенд и фронт енд.
2. Премести бекенда си в новото репозитори.
3. Изтрий старото.

Забележка: Ако не искаш да си изгубиш хисторито, опитай да го пруименуваш. Как става това - прочети [тук](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository).

Вариант 2.

1. В руут на текущото репозитори създай нова папка за бекенда.
2. Премести всичко в новата папка.
3. Можеш да комитнеш в нея, напр:

```
git add .
git commit -m "Transfer everything to new subproject"
git push
```

Поздрави,
Л.

**Comment by emil2romanov** [comment]
Благодаря много!
