### ISSUE TITLE
Wrapper Class vs Primitive Class Variables

### ISSUE THREAD

**Issue by ilambrev** [luchob/softuni-sep-2023#13]
Здравей Лъчо,

Във връзка със създаването на ентити-та ми дойде един сигурно вече омръзнал ти въпрос "Кога се ползват примитивни и кога се ползват референтен тип променливи?".

Четох различни материали из Интернет, в които е описано, че за да бъде една програма напълно обектно ориентирана трябва да се ползват референтен тип променливи, но пък примитивните са доста по-бързи (затова се ползват главно при I/O операции). От друга страна при сериализиране на примитивен тип променливи те първо трябва да се преобразуват в обекти, чрез ползване на wrapper класовете, докато ползването на референтен тип прави кода serializable. Примитивните стойности имат някаква стойност по подразбиране, при референтните типове стойността по подразбиране е NULL и т.н.

Мисля, че би било полезно , ако има време след някоя лекция, да изясниш този въпрос и да обясниш как се процедира в реалната практика при създаването на ентититата.

**Comment by luchob** [comment]
Отговорено.
