### ISSUE TITLE
Проблем с fork на репо-то

### ISSUE THREAD

**Issue by ilambrev** [luchob/softuni-sep-2023#2]
Здравей Лъчо,
Имам някакъв проблем с това репо. Вчера след като го създаде пробвах да го fork-на. Github ми поиска автентикация, след което опцията за fork изчезна. При мен обаче не се вижда репо-то като форкнато. Дали се получава така защото все още е празно?

**Comment by luchob** [comment]
Предполагам, защото не можеш да го форкнеш повече от един път. 
Вече не е празно. Ако искаш изтрий форка си и пробвай още веднъж.

**Comment by ilambrev** [comment]
Вече всичко е наред. След като се изпълни със съдържание репо-то отново при мен се появи опцията за fork и всичко с форкването мина както трябва. :)

**Comment by luchob** [comment]
Cool! Има и още неща в репото - template-и за новите issue-s :-)
Като имаш такова нещо в root-a на репото, когато ти отварят ново issue може да се избере някой от темплейтите.

Поздрави,
Л.
