### ISSUE TITLE
Проблем при изпращане на мейл към GMAIL

### ISSUE THREAD

**Issue by gboteva** [luchob/softuni-sep-2023#24]
*Връзка към проекта:*

https://github.com/gboteva/Child-Kitchen

Здравей, Лъчо!

Докато се борех с изпращането на email към GMAIL се натъкнах на следния проблем: пращам мейл с подател определен мейл, получен от контактната форма в приложението, но в GMАIL се получава мейл от "мен", т.е. игнорира се подадения в метода подател, и за подател се слага юзъра, който е конфигуриран в приложението.
Четох в нета и видях, че някои smtp сървъри не позволяват подобни действия и игнорират част от информацията, подадена от приложението. Все пак има ли някаква вратичка за по-коректна работа на app-a?

Ако имаш време огледай приложението и дай някакъв feedback за него.

Благодаря ти предварително!
Поздрави!

**Comment by luchob** [comment]
Здравей! 

За съжаление няма начин да използваш личния си акаунт в gmail без да ти смени from, но и reply-to. Причината допускам е най-вече SPAM. За development и демо бих не посъветвал да използваш един много лесен tool - нарича се Mail Hog -> https://github.com/mailhog/MailHog

Та въпросния туул е SMTP сървър + UI (http://localhost:8025/) в който можеш да "получиш" всичко изпратено през този SMTP сървър. От доста време го ползваме и в работата си, като пък на PROD ползваме отново Google SMTP, но вече със собствен домейн + разни платени фичъри.

Между другото можеш да плащаш и писма в HTML формат ако ти се занимава. Става като инжектираш template engine + нещо от сорта на това дето правихме тук https://github.com/luchob/softuni-sep-2023/blob/main/thymeleaf-pure/src/main/java/org/example/Main.java

Но без template resolver.

Проектът ти е доста над материала, който сме взели до момента :-) Ако ми остане време ще погледна по-внимателно ентититата другата седмица.

Поздрави,
Л.
