### ISSUE TITLE
Съвет относно използване на spring batch в проект

### ISSUE THREAD

**Issue by magdalenavelikova** [luchob/softuni-sep-2023#25]
*Връзка към проекта:*

_Поставете [връзка](https://github.com/magdalenavelikova/boxerclub-bg) към проекта си тук._

*Кратко описание:*

Здравейте, това е проекта, който започнах и засега нямам проблеми, но имам още доста работа.
Днес имплементирах spring batch и въпросът ми към Вас е, мислите ли, че е удачно да го ползвам за init() на базата данни, за да изчитам данните от .csv file. Всъщност идеята е да мигрирам повечето от данните от работещ wordpress website, който "възложителят" е ползвал.

**Comment by luchob** [comment]
Здравей!

Както може би си забелязала, batch съвсем не е тривиален за работа и подкарване :-) Ползвал съм го преди години за периодичен импорт на големи csv файлове от външна система и помня че имаше интересни функции като рестарт на джобове, пропускане, статистики и т.н. Дори и къстъм скоупове на бийноветe.

Ако е за еднократен импорт вероятно би не бих го ползвал в истински проект, т.к. е достатъчно сложен и труден за подкарване, тестване и т.н. Тоест трябва да е за нещо дето наистина се случва периодично и обемите на входните данни са много големи.

Ако е с образователна цел, както може би е твоя случай - определено си струва. Но пак подчертавам че не е тривиално :-)

Поздрави,
Л.

**Comment by magdalenavelikova** [comment]
Здравей, благодаря за отговора. Аз успях да го имплементирам, но точно защото знам, че се използва за импорт на големи масиви от данни, което моят проект не налага, зададох въпроса си. В доста от обявите за работа го има като изискване и затова реших да го поразуча на базово ниво. Въпросът е, след това като го видят да се използва за такава глупост ще си кажат "Тази пък, изобщо не знае за какво се ползва?" или "Е, поне го е виждала!" :)

**Comment by luchob** [comment]
Здравей!

Проектът е учебен, така че поне според мен ще остави позитивно впечатление. Особено за такава интеграция, която изобщо не е тривиална. Но е също и малко субективен, защото много зависи и от интервюиращия. 

Може да те питат въпроси от сорта на "как минава перфектния работен ден" до "как се имплементира къстъм бийн scope". Първият е ясен :-) 

Интервюиращите, които познавам и с които съм говорил биха се отнесли сериозно към успешна интеграция на batch.

Успех!
