### ISSUE TITLE
Обвързване на едно падащо меню с друго

### ISSUE THREAD

**Issue by D00ktora** [luchob/softuni-sep-2023#26]
*Връзка към проекта:* [връзка](https://github.com/D00ktora/BulgarianTripPlanner)

*Кратко описание:*

На едн-пойнта: http://localhost:8080/users/profile/motorcycle, опитвам да направя едното падащо меню да се визуализира спрямо другото.

Възможно най-накратко опишете:

1. Какво очаквате да се случи -> В полето Made избирам производител, а в полето Model  да ми визуализира енъм който е за определения производител.
2. Какво всъщност се случва -> Към момента нищо.
3. Какво опитахте ->  Три дена търся вариант в нета, консултирах се и с чата и пак не можах да го направя.

*Стъпки за репродуциране:* -> Стартираш проекта, влизаш на горепосочения енд-пойнт и в първия дроп даун избираш 1-вия производител "AbeStar", след което във второто поле искам да се визуализира енъма на този производителм къде ще добавя статично всички модели произведени от него.

Опишете възможно най-лесните стъпки, с помощта на които може да се репродуцира проблемът.

**Comment by luchob** [comment]
Здравей!

Най-елементарния вариант е да генерираш някакъв код в страничката си от сорта на:

```
var bikesInfo = {
        Honda:  ["Hornet", "NC750S", "Africa Twin"],
        Kawasaki: ["Versys 1000", "ER6N", "H2"]
    }
``` 

След това пътят е осеян с малко JS. Набързо натраках едно примерче, надявам се е достатъчно просто. Виж го ето [тук](https://jsfiddle.net/m53knp2j/3/).

Другия вариант е динамично да ги зареждаш с fetch+REST но там става и малко по трудничко и ще се наложи да си поиграеш.

Поздрави,
Л.

**Comment by luchob** [comment]
BTW преди малко женичката се ядосваше. Търси за малката някакви кецове отколешна пуберска мечта и ги [намира за 76 лв](https://www.fashiondays.bg/p/%D0%A3%D0%BD%D0%B8%D1%81%D0%B5%D0%BA%D1%81-%D0%BA%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8-%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%BD%D0%B8-%D0%BE%D0%B1%D1%83%D0%B2%D0%BA%D0%B8-%D0%96%D0%B5%D0%BD%D0%B8-converse-p820991-1/).

Да, ама като избере номер стават внезапно 165, а шансовете на малката 0 :-) . Което според мен е леко некоректно, но технически погледнато цената е вързана за дропдауна както ти искаш и като се сменя дропдауна се сменя и цената. Вътре в HTML-a ако се разтърсиш има подобни динамично генерирани JS снипети за всеки размер:

```
[{
    "color": "black",
    "size": "3.5",
    "price": 165.99,
    "rrp": 165.99,
    "cmmp30": null,
    "cmmp30StartDate": null,
    "priceOptions": {
      "display_product_price_cmmp30": false,
      "display_original_price": false,
      "display_discount_as": "percent",
      "display_price_info": false,
      "discount_value": 0
    },
    "advantage": 0,
    "productId": 2547970,
    "allowedToBuy": true,
    "low_stock_alert_message": "",
    "availability_group_id": "availability_id_3",
    "availability_stock_title": "",
    "availability_stock_subtitle": ""
  }
  ...
  {
    "color": "black",
    "size": "11.5",
    "price": 76.99,
    "rrp": 165.99,
    "cmmp30": 72.99,
    "cmmp30StartDate": null,
    "priceOptions": {
      "display_product_price_cmmp30": false,
      "display_original_price": true,
      "display_discount_as": "absolute",
      "display_price_info": true,
      "discount_value": 0
    },
    "advantage": 89.00000000000001,
    "productId": 2547971,
    "allowedToBuy": true,
    "low_stock_alert_message": "\u041e\u0441\u0442\u0430\u0432\u0430\u0442 2",
    "availability_group_id": "availability_id_3",
    "availability_stock_title": "",
    "availability_stock_subtitle": ""
  }]
```

Само два от размерите са с ниската цена. Т.е. задачата им е била:

* покажи минималната цена от всички номера
* напиши JS който при смяна на номер да показва истинската цена

**Comment by thrako** [comment]
Колега, не съм имал време да заредя проекта, но питането като функционалност много прилича на доработката, която правих за mobilele (https://github.com/thrako/thrako-softuni-sep-2023/tree/main/mobilele). Разликата е, че там `OnFocusOutEvent` попълвам dataset (https://github.com/thrako/thrako-softuni-sep-2023/blob/main/mobilele/src/main/resources/static/js/codename-ferrari.js), а ти искаш да ти се попълва падащо меню. Мисля, че можеш да преизползваш голяма част от кода.

Поздрави,
Траян
