### ISSUE TITLE
CriteriaQuery problem

### ISSUE THREAD

**Issue by andy489** [luchob/softuni-sep-2023#29]
*Връзка към проекта:*
[връзка към проект](https://github.com/andy489/Mobilele)

*Кратко описание:*
Specification API не иска да захапе.
Очаквам да мога да търся в базата данни по дадени критерии, но не успявам да ги натрупам като предикати.

*Стъпки за репродуциране:*
1. Смяна на паролата за базата данни
2. Клик на Offers tab-a (не е нужна регистрация или логване)
3. В полетата с етикет "Vehicle year" въвеждаме "2002" за "Year from..." и "2006" за "Year to..." (това трябва да филтрира само първите две коли)
4. Клик на Advanced search бутона 
5. Клик единствено на checkbox-a "Climatic" (от вече филтрираните две коли трябва да остане само тази с климатик)
6. Клик на Search бутона

Резултат: за съжаление не филтрира.

Опитах чрез дебъг в OfferSpecification класа от пакета repository да проследя какво се случва. Забелязах че данните пътуват както се очаква и че влизаме в if-oвете, които се очаква за да натрупаме предикатите, НО изглежда не ги използва, а ги игнорира по някаква странна причина. Help...

**Comment by luchob** [comment]
Здравей!

За съжаление този начин на съставяне на предикати няма да работи в тази версия на спринг. Погледни, моля те тук -> https://github.com/luchob/softuni-feb2023/issues/34

Ако пак има драма отвори наново същия бъг и ще го борим.

Поздрави,
Л.

**Comment by andy489** [comment]
Здравей, 
бях стигнал до същия workaround, но го изтрих и го пратих неработещо като се надявах тайничко да има нещо по-елегантно от това. Защо бягам от това? Защото въпреки, че по този начин работи, в браузъра остава следната заявка от сценария описан по-горе:

http://localhost:8080/offers?model=&descriptionInfix=&engineType=&transmissionType=&yearFrom=2002&yearTo=2006&mileageFrom=&mileageTo=&minPrice=&maxPrice=&_awd=on&_xenonLights=on&climatic=true&_climatic=on&_isofixSystem=on&_parktronic=on&_antiBlockingSystem=on&_navi=on&_cabriolet=on&_leasing=on&_bluetooth=on&perPage=&sortDirection=&sortBy=

Тоест, тези параметри, които НЕ сме ги сет-нали, въпреки това се наливат в URL-а като query параметри но без съдържание, което може би е малко грозно, защото същия резултат ще даде и следната окастрена заявка:

http://localhost:8080/offers?yearFrom=2002&yearTo=2006&climatic=true
