### ISSUE TITLE
Проблем с Pageable

### ISSUE THREAD

**Issue by Hristinchet0** [luchob/softuni-sep-2023#3]
Здравейте. Започнах да пиша моя проект за финалния изпит.

Срещам проблеми с Pageable.

Когато визуализирам всички продукти в онлайн магазина, няма проблем Pageable работи.
Но когато клина на някоя от наличните категории ми гърми и то някакъв проблем в thymeleaf-a.

Това е грешката.

![screencapture-localhost-8080-shop-category-2-2023-09-15-00_19_19](https://github.com/luchob/softuni-sep-2023/assets/105784923/92e92329-f24b-4f95-8307-36e208dc3fe9)

Това е таст от html-a

![shopHTML](https://github.com/luchob/softuni-sep-2023/assets/105784923/d3003d55-661f-4e1a-811c-f67d310fde97)

Това част от контролера

![shopController](https://github.com/luchob/softuni-sep-2023/assets/105784923/2c09401e-228e-4d3e-bd85-5f4771fb303f)

PorductService:

![productService](https://github.com/luchob/softuni-sep-2023/assets/105784923/1d610336-7413-4302-bdfb-7f6adae10c22)

Видео:

https://github.com/luchob/softuni-sep-2023/assets/105784923/631e2410-9508-4593-8148-509a8ffd1e13

Преди да добавя Pageable всичко си работеше както трябва.

Благодаря предварително.

**Comment by Hristinchet0** [comment]
Има някакво развитие...
 ![image](https://github.com/luchob/softuni-sep-2023/assets/105784923/c2706b72-882f-4d8c-82ab-78455b05c4ac)

**Comment by luchob** [comment]
Здравей!

Може ли да погледна проекта, така ми е много трудно да ти кажа къде е проблема (в първия ексепшън видях само, че си подала List вместо Pageable. Ако репозиторито ти е private по някаква причина и искаш да остане такова, може да ме направиш Collaborator (Settings -> Collaborators -> Add people). Така бих могъл да съдействам.

Поздрави,
Л.

**Comment by Hristinchet0** [comment]
Да, private е проекта, сега ще ви добавя.

**Comment by luchob** [comment]
Здравей!

Причината за последната грешка след напредъка е тук:

```
public interface ProductRepository extends JpaRepository<ProductEntity, Long> {
    Page<ProductDetailDto> findByCategoryId(int id, Pageable pageable);
}
```

`ProductRepository` e репозитори, което предоставя достъп до `ProductEntity`, а не до `ProductDetailDto`. По подразбиране спрниг не би могъл да знае как да обърне `ProductEntity` в `ProductDetailDto`. Затова и ти казва, че не знае как да направи `Page<ProductDetailDto>`. Но би могъл `Page<ProductEntity>`.

Поздрави,
Л.

**Comment by Hristinchet0** [comment]
Благодаря много... Явно грешка от недоглеждане... и бързане... който пише код в през ноща, така ще е. Продължавам сега напред с останалите неща. Оставям ви достъпа до репото, ако отново имам нужда от помощ. Хубав и успешен ден.
