### ISSUE TITLE
Проблем със security

### ISSUE THREAD

**Issue by VasilSV** [luchob/softuni-sep-2023#33]
*Връзка към проекта:*

_Поставете [връзка](https://github.com/) към проекта си тук._ https://github.com/VasilSV/MultiPlace

*Кратко описание:*
Здравейте,
предварителни извинения, но когато имате време бихте ли погледнали къде не съм направил security-то както трябва.
1. Това което ме дразни, е че при този вариант ми изкарва на localhost:8080 - директно login  и ако не се логна с валиден user не ме допуска до приложението.
2.Ако сложа   @Bean на defaultSecurityFilterChain гърми с грешка че не знае кои шаблони са "Spring MVC patterns" или не.

Възможно най-накратко опишете:

1. Какво очаквате да се случи
2. Какво всъщност се случва
3. Какво опитахте

*Стъпки за репродуциране:*

Опишете възможно най-лесните стъпки, с помощта на които може да се репродуцира проблемът.

**Comment by luchob** [comment]
Здрасти, Васко!

Мисля, че:

1. Тази анотация не ти е необходима `@EnableWebSecurity`
2. Това депендънси трябва задължително да ти е със скоуп тест, т.к. инсталира h2 конзола с разни допълнителни сървлети и т.н.
```
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>//<-тук
        </dependency>
``` 

Поздрави, 
Л.

**Comment by luchob** [comment]
Привет!

Ако загледаш лога, ще забележиш това:

```
... Securing DELETE /api/users/4
... Invalid CSRF token found for http://localhost:8080/api/users/4
... Responding with 403 status code
```

Накратко, в заявката би трябвало да има и CSRF тоукън. Може да подходиш по различен начин, но [тук](https://github.com/luchob/pathfinder/blob/9dc5ae639b7d674ab43048ec7b8d28779e561e36/src/main/resources/templates/fragments/commons.html#L7) има пример как да го сложиш в хедърите, а [тук](https://github.com/luchob/pathfinder/blob/9dc5ae639b7d674ab43048ec7b8d28779e561e36/src/main/resources/static/js/comments.js#L4) как да го вземеш.

Поздрави,
Л.

**Comment by VasilSV** [comment]
Много Благодаря отново!

**Comment by VasilSV** [comment]
Здрасти Лъчо , 
пак съм аз и извинения за късния час!
значи с две думи казано тоя път бързам да те питам защото само 3 дена се блъскам за сега  а вече няма време и си научих урока че колкото по рано те питам толкова по добре за  мен :)

1. Големия тормоз ми е че се опитвам в all.html  чрез BuyGloves.js и OrderingGloves.js да направя успешен Order на Gloves  със запазване в базата и намапване с customer и tool. Гърми ми при първата проба а след това не , като ми изкарва грешка която ме отчайва( грешно ли подхождам!? )
2. Някаква идея защо tymeleaf-a ми се инати и не желае да се показват грешките за невалидни входни данни / мисля че само auth-register съм написал /
3. Какво мислиш за това което съм написал за момента !?  достатъчно ли е !? някакви съвети ?

Предварително Благодаря и лека нощ :)

**Comment by luchob** [comment]
Здравей!

Относно проблем но.1, допускам че става въпрос за тази грешка и прилежащите и ексепшъни (хубаво е да слагаш конкретната грешка в описанието):

```
2023-12-04T08:09:47.938+02:00  WARN 83973 --- [io-8080-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `java.util.ArrayList<com.example.multiplace.dtos.ToolDTO>` from String value (token `JsonToken.VALUE_STRING`)]
```

Причината е, че десериализираш `OrdersDTO`:

```
    @PostMapping
    public ResponseEntity<OrdersDTO> createOrder(
            @RequestBody OrdersDTO ordersDTO,
            UriComponentsBuilder uriComponentsBuilder)
``` 

JSON-a който идва е:

```
{
  "orderedTools": "Gloves",
  "quantity": "2"
}
```

Имаш orderedTools - което е стринг и в ДТО-то:

```

    public OrdersDTO setOrderedTools(List<ToolDTO> orderedTools) {
        this.orderedTools = orderedTools.stream()
                .map(toolDTO -> new ToolEntity()
                        .setId(toolDTO.getId())
                        .setToolName(toolDTO.getToolName())
                        .setDescription(toolDTO.getDescription())
                        .setPrice(toolDTO.getPrice()))
                .collect(Collectors.toList());
        return this;
    }
```

Няма начин как да се намапне коректно. В допълнение ще кажа, че не е хубаво да използваш ентити обекти в DTO.

**Comment by luchob** [comment]
Относно втория въпрос, предполагам че имам идея.

Във формата имаш:

```
    <form
            th:action="@{/users/register}"
            th:method="post"
            th:object="${userRegistrationDTO}"
```

Тук DTO е с главни букви. В контролера имаш:

```
addFlashAttribute("userRegistrationDto", userRegistrationDTO)
```

Тук обаче, името е `userRegistrationDto`, което е само с една главна буква.

Относно третия въпрос - дали е достатъчно - мисля, че от софтуни би трябвало да ти отговорят на въпроса, т.к. те дават заданието. Другото е дали ти си доволен от направеното :-)

Поздрави,
Л.

**Comment by VasilSV** [comment]
Здрасти Лъчо, благодаря за отговорите особенно за thymeleaf  ... 50 пъти гледах ...

срам ме е пак да питам ама като се сещам че остават 2 дена и ми става лошо :(
поправях , писах  но не мога да запазя ордер в базата. Целта ми беше при натискане на id="ordersSumBtn" в all.html да запиша визуализираната поръчка в базата , но някъде се разминавам. Докарах се до там че не ми гърми в момента нищо ама  не записва ордер( само за  tool -> Gloves може да се пробва  ...) . Моля погледни когато имаш време. Ще съм благодарен за насока и  съвет.

**Comment by luchob** [comment]
Привет!

Най-важното е да успееш сам да провериш къде е проблема. Как да стане това? Например пускаш дебъгер и слагаш брейк пойнт в контролера и виждаш, че тази валидация:

```
    if (ordersDTO == null || ordersDTO.getOrderedTools() == null
           || ordersDTO.getOrderPrice()==null || ordersDTO.getOrderedTools().isEmpty()) {
        return ResponseEntity.badRequest().build();
    }
``` 

не минава и връщаме 400. Това е защото `ordersDTO.getOrderPrice()==null ` е true. Т.е. няма orderPrice. Това може да се потвърди, и от браузъра, от dev tools. В network таба може да видиш JSON-a който върви по мрежата:

```
{
  "orderedTools": [
    {
      "toolName": "Gloves",
      "description": "Работни ръкавици",
      "price": 3
    }
  ],
  "quantity": "2"
}
```

Наистина няма order price. А освен това ми е малко мъгляво дори полето quantity какво ще отразява ако имаш 3 броя orderedTools, например... 

Та като има такава грешка -> debugger, ако се наложи network и нещата ще станат очевидни :-)

Поздрави,
Л.
