### ISSUE TITLE
Добавяне на снимка към профила

### ISSUE THREAD

**Issue by D00ktora** [luchob/softuni-sep-2023#35]
Как да добавим снимка в профила и да я запишем в базата. Като потребителя, да може да добави без значение какъв размер на файла и след това този файл да бъде компресиран и запазен в базата, за да може да се използва после или ако не в базата къде?
Лъчо ако може да го покажеш на някоя лекция, ще съм много благодарен. 
Търсих в нета и колкото повече търся толкова повече се отдалечавам от това нещо.

**Comment by luchob** [comment]
Привет - тук има примерно приложение с ъплоуд на файл, а после и даунлоад -> https://github.com/luchob/fileupload
