### ISSUE TITLE
WISH

### ISSUE THREAD

**Issue by DesZafirova** [luchob/softuni-sep-2023#36]
Здрасти Лъчо, дали можем да направим reCaptcha?

**Comment by luchob** [comment]
Здрасти, Деси! 

Ако ми остане време, ще си поиграя. 

Едно време бях слагал v2 - там дето цъкаш "I'm not a robot."  Но това вече е демоде и има v3, която е съвсем различна и при нея не цъкаш нищо. Вместо това то те следи какво правиш, праща някакъв тоукън на сървъра и през REST викаш тяхното API с тоя тоукън. Те ти връщат едно число между 0 и 1 дето съответства на вероятността това да е бот. Според гугъл, разбира се :-) Какво точно прави - честно казано ми е мъгла и не съм чел по въпроса.

Но... Едва ли е особено трудно да се интегрира. Ще проверя. Представям си малко C&P на JS и накрая един тоукън заминава към сървъра, а от сървъра към гугъл.

В крайна сметка имаме още три лекции, които са основно за забавления. :-)

Поздрави,
Л.

**Comment by luchob** [comment]
Поиграх си днес и тръгна :-) 
Допускам, че за 30-40 мин ще можем да го накодим в регистрацията. Даже ми иска да го направим и с WebClient, защото RestTemplate-a става все по-демоде. Поне за мен е интересно да си цъкаме някакви по-нови неща.

**Comment by luchob** [comment]
Done :-)
