### ISSUE TITLE
Admin Controller Issue

### ISSUE THREAD

**Issue by AlexanderKK** [luchob/softuni-sep-2023#37]
Здравейте, тъй като имам управление на роли и потребители от потребител с роля admin се чудех дали да направя пътищата да започват с /admin и всичката функционалност да е изнесена в AdminController, или за потребители да използвам пътища /users/** и за роли /roles/** със съответните UserController И RoleController?
Поздрави, Александър

**Comment by luchob** [comment]
Привет!

В повечето случаи бих избягвал да именувам пътищата спрямо ролите на потребителите. Това е защото един и същи път може да се споделя между admin и user, например ъпдейт на профил, смяна на адрес и т.н. По-хубаво е като че ли пътя да съответства на ресурса който се управлява - /user, /order, /account и т.н.

Поздрави,
Л.

**Comment by AlexanderKK** [comment]
Много благодаря, това ми беше голяма чуденка.
