### ISSUE TITLE
Searching functionality

### ISSUE THREAD

**Issue by rado-bochukov** [luchob/softuni-sep-2023#43]
Привет, Лъчо!

Извинявам се , че така в последния момент пиша, но имам проблем с имплементирането на функционалност за търсене по различни критерии в моя проект, следвайки записките ми и кода пот репото на мобилеле от лятото на 2022 (нещо не мога да намеря видеото , по което си водих тези записки).

Прилагам линк към класа ArtistSpecification.

Проблема идва от това че когато UserRepository изпълнява метода search с аргумент ArtistSpecification , връща като резултат всички юзъри (просто изпълнява findAll()) - въобще не взима под внимание предиката който му подавам.

Можеш ли да погледнеш и надявам се да намериш къде бъркам?
Благодаря предварително!

https://github.com/rado-bochukov/archviz-arena/blob/main/src/main/java/com/example/archvizarena/repository/ArtistSpecification.java

**Comment by luchob** [comment]
Привет! 

Този начин няма да работи в новите версии на спринг. 

Погледни тук -> https://github.com/luchob/softuni-feb2023/issues/34

Поздрави,
Л.
