### ISSUE TITLE
Проблем при тестовете с @WithMockUser

### ISSUE THREAD

**Issue by rado-bochukov** [luchob/softuni-sep-2023#44]
Привет , Лъчо!

Имам проблем при интеграционните тестове!

Опитвам се да тествам създаването на Портфолио проект, про което ми е нужно да подам принципала от контролера в сървиса за да мога да го посоча като автор.
В тестовете обаче, въпреки че моквам принципал вече доста пъти ми гърми с NullPointerException че не го намира.
В секюритъ контекста съм настроил то този урл да имат достъп само юзъри, които са с роля "ARTIST" , но не мисля че това е проблема в момента.
Можеш ли да погледнеш и да разбереш от къде идва този null и как бих могъл да подам коректно принципал в тестовете.

Прилагам скрийншот . Мисля ,че по лесно ще даде представа. А линк към проекта е :->
https://github.com/rado-bochukov/archviz-arena/blob/main/src/test/java/com/example/archvizarena/web/ProjectUploadControllerTest.java

Благодаря!

![tests](https://github.com/luchob/softuni-sep-2023/assets/122348543/c7390e2e-093e-4f4f-96f2-ab4d4f157806)

**Comment by luchob** [comment]
Здравей!

Ще ти дам една бърза подсказка, т.к. не мога повече в момента :-) Имаш `WithMockUser+@AuthenticationPrincipal ArchVizArenaUserDetails`. 

Това няма как да сработи, т.к. спринг тест не би могъл да знае как да превърне UserDetails-а който е създал с WithMockUser точно в ArchVizArenaUserDetails, а не например в LuchoUserDetails или нещо дружо. И... инжектира null. Затова има една друга анотация - WithUserDetails. Документацията е ето [тук](https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/test-method.html#test-method-withuserdetails).

Ето какво пише:  "While @WithMockUser is a very convenient way to get started, it may not work in all instances. For example, it is common for applications to expect that the Authentication principal be of a specific type. "

Надявам се това да помогне, ако не отвори наново issue-то.

Поздрави,
Л.

**Comment by rado-bochukov** [comment]
Добро утро, Лъчо!

Благодаря за разясненията.
Докато се мъчих сам вчера бях минал и през това , но не ми разпознаваше userDetailsServiceBeanName-a. СЛед твоя отговор задълбах малко повече и с помощта и на гпт-то разбрах, че трябва да направя TestConfig клас в който да добавя като Bean ArchVizArenaUserDetailsService. 

Вече го разпознава, но сега изскача друг проблем- въпреки че съм задал в @BeforeEach да създава юзър, който да ползвам за принципал . всеки път теста гърми, защото не го намира в базата.
Много лошо е това, защото в повечето от методите в контролерите ми е нужен принципала и ми връзва ръцете в момента .
Според мен правя грешка някъде в подаването на UserRepository. Въпреки че @Autowired би трябвало да се погрижи да е едно репозитори навсякъде. При дебъг виждам че сейфа юзъра в репозиторито, но дойде ли момента на теста не го намира.

Ето линк към TestConfig-> https://github.com/rado-bochukov/archviz-arena/blob/main/src/test/java/com/example/archvizarena/testConfig/TestConfig.java
A това е линк към класа за тестване->  https://github.com/rado-bochukov/archviz-arena/blob/main/src/test/java/com/example/archvizarena/web/ProjectUploadControllerTest.java

![test2](https://github.com/luchob/softuni-sep-2023/assets/122348543/769d2cfa-7d45-4fa7-b169-1ea8657a5e19)
Благодаря отново!

**Comment by luchob** [comment]
Здрасти!

Щом гпт-то не може да отговори, тегава работа и наистина звучи много лошо ;-) Но нека опитаме...

_Вече го разпознава, но сега изскача друг проблем- въпреки че съм задал в https://github.com/beforeeach да създава юзър, който да ползвам за принципал . всеки път теста гърми, защото не го намира в базата._

Тук може би вината е моя, защото прибързано ти пратих не най-последната версия на документацията. Имаше едно бъгче - https://github.com/spring-projects/spring-security/issues/6591

Та хората го пооправиха и сега в [последната версия на документацията](https://docs.spring.io/spring-security/reference/servlet/test/method.html#test-method-withuserdetails) е записано:

> By default, the SecurityContext is set during the TestExecutionListener.beforeTestMethod event. This is the equivalent of happening before JUnit’s @Before. You can change this to happen during the TestExecutionListener.beforeTestExecution event, which is after JUnit’s @Before but before the test method is invoked:
> 
> @WithUserDetails(setupBefore = TestExecutionEvent.TEST_EXECUTION)

Преведено, означава че би могъл да си организираш теста по следния начин:

```
    @BeforeEach
    void setUp() {
        ...
        userTestDataUtil.createArtist(TEST_ARTIST_USERNAME);
        ...
    }

    @Test
    @WithUserDetails(
        value = TEST_ARTIST_USERNAME,
        userDetailsServiceBeanName = "ava",
        setupBefore = TestExecutionEvent.TEST_EXECUTION
    )
    void TestUserUploadProject() throws Exception {
       ....
    }
```

Поздрави,
Л.

**Comment by rado-bochukov** [comment]
Много, много благодарности!

Развърза ми ръцете!

Поздрави!
