### ISSUE TITLE
Проблем с Fetch и Java Script

### ISSUE THREAD

**Issue by GeriMD** [luchob/softuni-sep-2023#46]
*Връзка към проекта:*
[
_Поставете [връзка](https://github.com/) към проекта си тук._](https://github.com/GeriMD/services-for-you)

Здравейте! Днес се захванах да правя Fetch-а, който изискват за изпита, но не съм карала курса за front-end и java script-a го преписах от вашия, когато го отворя от иконките на браузърчета, които излизат горе в дясно в IntelliJ върви js-a, но когато стартирам проекта Rest controller-a ми връща просто json, което значи, че back-end-a работи правилно, но не мога да разбера причината, поради която front-end-a не се зарежда. Идеята на това, което искам да направя с тази заявка е, да връща всички user-и, които са в таблицата със Seller-и и да мога да ги достъпвам от Админския панел, за да ги трия от базата.

Възможно най-накратко опишете:

1. Какво очаквате да се случи
2. Какво всъщност се случва
3. Какво опи

**Comment by luchob** [comment]
Здравей!

До колкото разбирам, искаш да заредиш скрипта, когато се обработи и отвори sellers.html. За да стане това, трябва да имаш някакъв метод в нормален контролер (а не RestController), който връща като име на View този темплейт. Например нещо такова:
```
@Controller
public class SellerController {
   @GetMapping("/sellers/all") 
   public String allSellers() {
     return "sellers";
   }
}
```

Тогава вътре в sellers.html да имаш нещо като:
```
<script th:src="@{/js/app.js}"></script>
```

Съответно да преместиш `app.js` в папката за статични ресурси както в mobilele са css-ите например.

Вместо това в момента имаш линк към рест контролера в nav-bar-a: http://localhost:8080/sellers/all

Този линк ти връща респонс който е json и затова браузъра го показва като такъв... 

Виж например как се инклудва този скрипт -> https://github.com/luchob/pathfinder/blob/9dc5ae639b7d674ab43048ec7b8d28779e561e36/src/main/resources/templates/route-details.html#L100

Поздрави,
Л.
