### ISSUE TITLE
Помощ 

### ISSUE THREAD

**Issue by D00ktora** [luchob/softuni-sep-2023#47]
Опишете накратко какво бихте искали да видите или да чуете в нашия курс.
-> курса свърши и получих задача за интервю, но изречението :” • Any framework can be used as long as it’s based on the Java or Kotlin programming languages.” Може да е нещо просто, но това значи ли че трябва да ползвам боотстрап или греша?

**Comment by luchob** [comment]
Здравей!

Не виждам какво общо има bootstrap с условието :-) Bootstrap e css/js библиотека - импортваш я в твоите HTML-и и можеш да си правиш разни готини компоненти - хубави бутончета, акордеони, попъпи и какво ли още не. [Пример](https://getbootstrap.com/docs/5.3/components/alerts/).

Със спринг видяхме какво може да се прави. Писахме на Java. Но както отбелязах, може да напишем едно спринг приложение не само на Java, но и на Kotlin или Groovy тъй като тези езици може да се компилират до същия байткод, който се изпълнява от JVM.

Та предполагам са ти дали някаква задача и искат да я напишеш на Java/Kotlin с фреймуърк като Спринг или пък някаква негова алтернатива - например [Quarkus](https://quarkus.io/get-started/) или [micronaut](https://guides.micronaut.io/latest/creating-your-first-micronaut-app-gradle-java.html) или нещо подобно. Ако задачката е някакъв web и трябва да е с нещо шаренко дали ще ползваш bootstap, или чист css или дори anglar/react предполагам не ги интересува.

Поздрави,
Л.

**Comment by D00ktora** [comment]
Отново благодаря 🍺
