### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by ilambrev** [luchob/softuni-sep-2023#7]
Здравей Лъчо,

Имам следното предложение - ако остане малко време в някоя от лекциите да обърнеш внимание на използването на Environment variables например в application.properties и application.yml за задаване на данни за идентификация (потребител и парола) и т.н.  както и къде и при какви ситуации е удачно да се ползват.

**Comment by luchob** [comment]
О, да, това задължително го гледаме. Особено като наближи часа за деплоймънт. Оставам отворено това issue.

**Comment by luchob** [comment]
Отговорено по време на лекцията :-)

Поздрави,
Л.

**Comment by ilambrev** [comment]
Лъчо, много благодаря за подробното обяснение за Environment variables. Много полезна информация!
