### ISSUE TITLE
Newbie here need advice

### ISSUE THREAD

**Issue by MartinKochanov** [luchob/softuni-sep-2023#9]
Здравей Лъчо. Имам готинка идея за моят проект, който ще бъде нещо като онлайн кино . Не ми се вижда много правилно ако филмите(виедата)  ги запазвам  в самата бааза данни. Има ли по-добър вариант за съхранението им? 

пп: Първоначалната ми едея беше да ги съхранявам в гугъл диск и в базата да пазя само линка към видеото, но не знам до колко е правилно и дали ще работи.

**Comment by luchob** [comment]
Здравей!

Обикновено когато става въпрос за подобно нещо, не обсъждаме дали е правилно или не, а по-скоро дали е евтино или не :-) 

Както и да е, в рамките на твоя личен проект може да опиташ и да разгледаш услугите на cloudinary, където има ограничен, но въпреки това подходящ за целта безплатен план:

https://cloudinary.com/pricing/compare-plans

Поздрави,
Л.
